### ISSUE TITLE
Requires flexsections course format

### ISSUE THREAD

**Issue by mudrd8mz** [3datax/moodle-mod_flexquiz#1]
The plugin requires https://moodle.org/plugins/format_flexsections be installed on the site but it does not declare that as a dependency.

As a result, adding an instance to the course ends up with:

![image](https://user-images.githubusercontent.com/85831/129205079-5ecaeb88-3851-4529-8a9a-a7dc3c7e7d4d.png)

Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Dependencies

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved with v1.0.2 (2f1d9d286d7800aee2865ff66e67f30c2d52a715)
