### ISSUE TITLE
multiple classes in single file and not using namespaces well

### ISSUE THREAD

**Issue by danmarsden** [3datax/moodle-mod_flexquiz#11]
Ideally a class file should only contain a single class - not hide multiple classes within the same file.

eg:
https://github.com/3datax/moodle-mod_flexquiz/blob/master/flexquiz/classes/child_creation.php#L423

you should also take a look at our auto-class loading/namespace rules
https://docs.moodle.org/dev/Automatic_class_loading

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved now in v1.0.6.4
