### ISSUE TITLE
Shows usernames

### ISSUE THREAD

**Issue by mudrd8mz** [3datax/moodle-mod_flexquiz#2]
The Performance page shows students and their usernames. That is quite uncommon in Moodle. Usernames are not normally displayed and some may even consider it security related (username is part of the authentication credentials).

it is much preferred to respect the `showuseridentity` setting. Please see https://docs.moodle.org/dev/User_fields for more details (note the new API is for 3.11 and higher only, there is a section on how to do it in older versions).

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved with v1.0.2 (2f1d9d286d7800aee2865ff66e67f30c2d52a715)
