### ISSUE TITLE
DB error after submitting the quiz

### ISSUE THREAD

**Issue by mudrd8mz** [3datax/moodle-mod_flexquiz#3]
After the student submits the quiz, an error is raised on my PostgreSQL installation

![image](https://user-images.githubusercontent.com/85831/129207663-c8201461-b0a0-470a-a072-eb50a6d4165c.png)

The essential part seems to be

```
ERROR: column "p.id" must appear in the GROUP BY clause or be used in an aggregate function
```

Whole error is:

An error occurred while processing your responses (Database transaction error (Invalid transaction commit attempt)). Click continue to return to the page you were on and try again.

More information about this error
Debug info: Invalid transaction commit attempt
Error code: errorprocessingresponses
Stack trace:

    line 2470 of /mod/quiz/attemptlib.php: moodle_exception thrown
    line 89 of /mod/quiz/processattempt.php: call to quiz_attempt->process_attempt()

Output buffer: <div class="notifytiny debuggingmessage" data-rel="debugging">Exception encountered in event observer '\mod_flexquiz\quiz_observers::handle_quiz_completion': Error reading from database (ERROR: column "p.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT p.id, sum(p.fraction) AS fractionsum, sum(p.ccas_this... ^ SELECT p.id, sum(p.fraction) AS fractionsum, sum(p.ccas_this_cycle) AS ccasum FROM m_flexquiz_grades_question AS p WHERE p.flexquiz_student_item=$1 [array ( 0 => '2', )])<ul style="text-align: left" data-rel="backtrace"><li>line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()</li><li>line 920 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()</li><li>line 1624 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()</li><li>line 1343 of /mod/flexquiz/classes/child_creation.php: call to moodle_database->get_record_sql()</li><li>line 266 of /mod/flexquiz/classes/quiz_observers.php: call to mod_flexquiz\child_creation\flexquiz_student_item->update_sum_grade()</li><li>line ? of unknownfile: call to mod_flexquiz\quiz_observers::handle_quiz_completion()</li><li>line 155 of /lib/classes/event/manager.php: call to call_user_func()</li><li>line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()</li><li>line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()</li><li>line 2288 of /mod/quiz/attemptlib.php: call to core\event\base->trigger()</li><li>line 2199 of /mod/quiz/attemptlib.php: call to quiz_attempt->fire_state_transition_event()</li><li>line 2456 of /mod/quiz/attemptlib.php: call to quiz_attempt->process_finish()</li><li>line 89 of /mod/quiz/processattempt.php: call to quiz_attempt->process_attempt()</li></ul></div>

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved with v1.0.2 (2f1d9d286d7800aee2865ff66e67f30c2d52a715)
