### ISSUE TITLE
Better not to use custom curl wrappers

### ISSUE THREAD

**Issue by mudrd8mz** [3datax/moodle-mod_flexquiz#4]
Moodle core ships with curl wrapper (class `curl`) that respects various site level settings and has security features built in. It's recommended to use it instead of direct low-level access to the cURL library as in your `curl_request_helper`

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue solved with v1.0.2 (2f1d9d286d7800aee2865ff66e67f30c2d52a715)

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved with v1.0.2 (2f1d9d286d7800aee2865ff66e67f30c2d52a715)
