### ISSUE TITLE
mysql specific sql

### ISSUE THREAD

**Issue by danmarsden** [3datax/moodle-mod_flexquiz#6]
I see some backticks in your sql which will trigger failures on postgres and other database types - please ensure that at minimum your plugin works in both mysql and postgres.

eg:
https://github.com/3datax/moodle-mod_flexquiz/blob/master/flexquiz/lib.php#L133-L139

**Comment by Andreas-3datax** [comment]
Thank you for the review and feedback.

Issue resolved now in v1.0.6.4
